name: Java Backend CI Workflow Compile Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the workspace repository tracking data
      uses: actions/checkout@v3

    - name: Set up Environment Development Kits JDK 17 Platform
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Execute Maven Compilation Phase Verification Action
      run: mvn compile
